/* Generated by Plankalkül Compiler
   Zane Hambly, 2025-2026
   
   "The calculus of plans" — Konrad Zuse, 1942
*/

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>

/* Runtime support (minimal) */
typedef struct { size_t len; int64_t* data; } pk_array_t;
typedef struct { int64_t _0; int64_t _1; } pk_tuple_t;
#define pk_len(a) ((a).len)
#define pk_get(a, i) ((a).data[i])


/* Plan: Factorial */
int64_t pk_Factorial(int64_t pk_v0) {
  /* Local variables */
  int64_t pk_z0 = 0, pk_z1 = 0, pk_z2 = 0, pk_z3 = 0;
  int64_t pk_r0 = 0, pk_r1 = 0, pk_r2 = 0, pk_r3 = 0;
  
  pk_r0 = 1LL;
  for (int64_t pk_z0 = 0; pk_z0 < pk_v0; pk_z0++) {
    pk_r0 = (pk_r0 * (pk_z0 + 1LL));
  }
  
  return pk_r0;
}

int main(void) {
  printf("Factorial(5) = %lld\n", (long long)pk_Factorial(5));
  printf("Factorial(10) = %lld\n", (long long)pk_Factorial(10));
  return 0;
}
